language: ruby

rvm:
  - 2.1
  - 2.2.5
  - 2.3.3
  - 2.4.0
  - ruby-head

gemfile:
 - Gemfile
 - Gemfile.v0.12

branches:
  only:
    - master

before_install: gem update bundler
script: bundle exec rake test

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
